### ISSUE TITLE
Eloquent DB Access

### ISSUE THREAD

**Issue by thedarkknight197** [zoilomora/doctrine-dbal-msaccess#12]
Hi,
i find your library from: https://github.com/zoilomora/laravel-msaccess

How could i use Eloquent after installed your library?

**Comment by simbirsky** [comment]
i have the same problem..
How can i use https://github.com/zoilomora/doctrine-dbal-msaccess? You can show examples?

**Comment by zoilomora** [comment]
This library is responsible for **supporting Doctrine DBAL**.
It would be necessary to make a Doctrine DBAL connector with Eloquent but not in this repository.
I have not used Eloquent for many years and right now I'm going through a personal situation that prevents me from getting involved in this project. 😔

**Comment by thedarkknight197** [comment]
No problem! Thank you so much for your work! :)
